### ISSUE TITLE
Doesn't work on Raspberry Pi 3

### ISSUE THREAD

**Issue by balpak** [thephez/data-diode#3]
Hi thephez,

Just tried to adopt your scripts for simple data transfer between 2 Pis and both send and receive works perfect on "Raspberry Pi Model B Plus Rev 1.2".  However something is wrong while running on "Raspberry Pi 3 Model B Plus Rev 1.3" and I guess it might be related to methods/properties of pyserial library. Both machines are running under latest Debian Buster Lite.

I know It was along time since you worked on this project but maybe you could have a look?

Thanks a lot.

[old Pi.txt](https://github.com/thephez/data-diode/files/4776232/old.Pi.txt)
[new Pi.txt](https://github.com/thephez/data-diode/files/4776233/new.Pi.txt)

**Comment by thephez** [comment]
Hey, I don't have time to look into this currently (actually don't even have 2 Raspberry Pis anymore), but there's a good chance something changed so that the setup script I was using no longer configures everything that is necessary for it to work. Unfortunately, I can't really give you much to go on. You may find something useful on the forums since this error would show up in other cases too (https://www.raspberrypi.org/forums).

**Comment by balpak** [comment]
No problem at all, after a bit of investigation I found how to fix it. Actually I did not use your script, only installed necessary Python and GPIO packages manually. For Pi3 I have to add 2 overlays to disable Bluetooth and enable CTS/RTS. Now everything woks fine with transfer speed ~ 60 Kb/s.

Thanks again for great job and good luck in your new projects.

**Comment by thephez** [comment]
Great! Glad you figured it out. You should be able to get substantially higher transfer speed if you need to by adjusting the serial settings. The process may be different now, but you can see how I was doing it here - https://github.com/thephez/data-diode/blob/master/transfer_data/scripts/sys_config.sh#L329
